### PR TITLE
Expose directivity, air absorption and distance attenuation calculate functions

### PR DESCRIPTION
**Pull request by GitGhillie**
Not sure if this is the best way, but it works

### CODE REVIEW

**Review by Aceeri — APPROVED** [review]
Could maybe make the model calculation methods take a `&self`, but I think it is fine either way here.

**Comment by GitGhillie** [comment]
I tried that initially but couldn't get it it to work. Guess my Rust improved a lot in 4 days because it was no problem at all lol

**Comment by GitGhillie** [comment]
Just noticed you were talking about a `&self` not just `self`. It will require a few more changes

**Comment by GitGhillie** [comment]
Like this?

**Comment by Aceeri** [comment]
Yep! :)

**Pull request merged**
